name: 'CIPokemon'

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Run Lint tests
        run: echo Run lin tests
  #
  #      - name: Run Lint
  #        run: ./gradlew lintDebug
  #
  #      - name: Upload html test report
  #        uses: actions/upload-artifact@v2
  #        with:
  #          name: index.html
  #          path: app/build/reports/lint-results-debug.html

  Unit_tests:
    needs: [ lint ]
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Run Unit tests
        run: echo Run unit tests

  #      - name: Checkout the code
  #        uses: actions/checkout@v3
  #
  #      - name: Run tests
  #        run: ./gradlew test
  #
  #      - name: Upload test report
  #        uses: actions/upload-artifact@v2
  #        with:
  #          name: unit_test_report
  #          path: app/build/reports/tests/testDebugUnitTest/

  instrumentation_tests:
    needs: [ Unit_tests ]
    runs-on: macos-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Run Instrumentation tests
        run: echo Run instrumentation tests

  #      - name: Checkout the code
  #        uses: actions/checkout@v3
  #
  #      - name: Run robolectric tests
  #        run: ./gradlew connectedCheck
  #
  #      - name: Upload test report
  #        uses: actions/upload-artifact@v2
  #        with:
  #          name: instrumentation_test_report
  #          path: app/build/reports/androidTests/connected/

  static_code_analysis:
    needs: [ instrumentation_tests ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Run Instrumentation tests
        run: echo Run instrumentation tests

      - name: set up JDK 11
          uses: actions/setup-java@v1
          with:
            java-version: 11

       - name: SonarCloud Scan
          run: ./gradlew app:sonarqube -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  package:
    needs: [ static_code_analysis ]
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: expense-manager.apk
          path: app/build/outputs/apk/debug/app-debug.apk